#!/usr/bin/env python3
"""Fold every release's digests into CHANGELOG.txt.

The changelog said "Digests for each release are in dist/pueo-<version>.sha256"
-- and the deploy's prune deletes exactly that file, while both the script's
own comment and the download page promised that a pruned release's digests
"stay in the changelog". They did not. Pruning was lossy in the one respect
it claimed not to be, and nobody would have found out until they went
looking for the digest of a release that had already gone.

This appends a digest table to the changelog, generated from the .sha256
files in dist/, so the claim becomes true before anything is deleted. The
table is the only place a pruned release's digests survive, which is why it
is regenerated rather than hand-kept.

    python tools/changelog_digests.py            rewrite the table
    python tools/changelog_digests.py --check    fail if it is out of date

Run it after the version bump and BEFORE make_release.sh cuts the archive.
Not after.

The order is not a style preference. CHANGELOG.txt ships inside
pueo-<version>-src.zip, so a table regenerated after the cut is a table the
published archive does not contain: the repo and the zip then disagree about
the digests of every earlier release, and the zip is the copy anybody
downloading will read. That happened at 0.4.19 and the release was cut
twice to fix it.
"""
import argparse
import glob
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
CHANGELOG = os.path.join(REPO, "CHANGELOG.txt")
DIST = os.path.join(REPO, "dist")

BEGIN = "Digests, every release"
RULE = "=" * 70


def vkey(v):
    return [int(x) for x in v.split(".")]


def current_version():
    """The version being built, which cannot be in this table."""
    src = io.open(os.path.join(REPO, "ESP32-DIV", "Branding.h"),
                  encoding="utf-8", errors="replace").read()
    m = re.search(r'PUEO_VERSION\s+"([^"]+)"', src)
    return m.group(1) if m else None


def collect():
    """Every release's digests except the one being built.

    The current version is skipped because it cannot be in here: this table
    lives in CHANGELOG.txt, the changelog ships inside pueo-<version>-src.zip,
    and the archive's own digest is taken after it is built. A version cannot
    record the hash of a file that contains the record.

    It is not a gap. The newest two releases are never pruned, and their
    digests are on the download page and in their own .sha256 beside them.
    What this table exists for is the releases that have gone.
    """
    skip = current_version()
    out = {}
    for f in glob.glob(os.path.join(DIST, "pueo-*.sha256")):
        m = re.fullmatch(r"pueo-([\d.]+)\.sha256", os.path.basename(f))
        if not m:
            continue
        rows = []
        for line in io.open(f, encoding="utf-8"):
            line = line.strip()
            if not line:
                continue
            digest, _, name = line.partition(" ")
            rows.append((name.lstrip("*"), digest))
        if rows and m.group(1) != skip:
            out[m.group(1)] = sorted(rows)
    return out


def table(rels):
    lines = [BEGIN, RULE, "",
             "SHA-256 of every artefact this project has published, including",
             "releases that have since been pruned from the download page. The",
             "page keeps the newest two plus 0.2.1 and 0.4.13; this keeps all",
             "of them, because a digest is the one thing about an old release",
             "that is still worth having after the file itself is gone.",
             "",
             "Generated by tools/changelog_digests.py from dist/*.sha256.",
             ""]
    for v in sorted(rels, key=vkey, reverse=True):
        lines.append("%s" % v)
        for name, digest in rels[v]:
            lines.append("  %s  %s" % (digest, name))
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rels = collect()
    if not rels:
        print("no dist/*.sha256 found", file=sys.stderr)
        return 1

    src = io.open(CHANGELOG, encoding="utf-8", newline="").read()
    nl = "\r\n" if src.count("\r\n") > (src.count("\n") - src.count("\r\n")) else "\n"

    body = table(rels).replace("\n", nl)
    i = src.find(BEGIN)
    # Same separator either way, or the first run and the --check that
    # follows it disagree about how many blank lines precede the table.
    head = src[:i] if i != -1 else src
    new = head.rstrip() + nl * 3 + body

    # The pointer at the top was aimed at the files, not at here.
    old_ptr = "Digests for each release are in dist/pueo-<version>.sha256.".replace("\n", nl)
    new_ptr = ("Digests for every release, pruned ones included, are at the end of"
               + nl + "this file.")
    if old_ptr in new:
        new = new.replace(old_ptr, new_ptr)

    if args.check:
        if new != src:
            print("CHANGELOG.txt's digest table is out of date; "
                  "run tools/changelog_digests.py", file=sys.stderr)
            return 1
        n = sum(len(v) for v in rels.values())
        print("digest table covers %d releases, %d artefacts" % (len(rels), n))
        return 0

    io.open(CHANGELOG, "w", encoding="utf-8", newline="").write(new)
    n = sum(len(v) for v in rels.values())
    print("wrote %d releases, %d artefacts" % (len(rels), n))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
