#!/usr/bin/env python3
"""Generate hud/hud_oui.cpp from the IEEE OUI registry cache.

Every entry is taken straight from tools/.oui-cache.csv (the IEEE MA-L list),
so the OUI->vendor claim is the registry's, not ours. Tactical priority: all
drone-maker blocks first (small sets, highest value), then IoT/DIY gear, then
the common phone/router brands (capped -- partial coverage, correct labels).

    python tools/gen_hud_oui.py        # rewrites hud/hud_oui.cpp
"""
import csv, io, re, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
CACHE = Path(__file__).resolve().parent / ".oui-cache.csv"
OUT = ROOT / "hud" / "hud_oui.cpp"

# (label, lowercased-org matcher regex, cap)  -- priority order, first match wins
VENDORS = [
    ("DJI",        r"\bdji\b",                 99),   # drone
    ("PARROT",     r"\bparrot\b",              99),   # drone
    ("SKYDIO",     r"\bskydio\b",              99),   # drone
    ("AUTEL",      r"\bautel\b",               99),   # drone
    ("ESPRESSIF",  r"espressif",               24),   # ESP32/IoT/DIY
    ("RASPBERRYPI",r"raspberry",               99),   # DIY/pentest
    ("MIKROTIK",   r"mikrotik|routerboard",    99),   # infra/pentest
    ("UBIQUITI",   r"ubiquiti",                16),
    ("APPLE",      r"\bapple\b",               12),
    ("SAMSUNG",    r"samsung",                 12),
    ("GOOGLE",     r"\bgoogle\b",               8),
    ("XIAOMI",     r"xiaomi",                   8),
    ("HUAWEI",     r"huawei",                  10),
    ("TP-LINK",    r"tp-?link",                10),
    ("NETGEAR",    r"netgear",                  8),
    ("CISCO",      r"\bcisco\b",               10),
    ("AMAZON",     r"amazon",                  10),
    ("MICROSOFT",  r"microsoft",                8),
    ("INTEL",      r"^intel\b",                10),
    ("REALTEK",    r"realtek",                 99),
]

def main():
    if not CACHE.exists():
        print("no registry cache; run check_oui_registry.py --fetch", file=sys.stderr); return 1
    rows = []
    with io.open(CACHE, encoding="utf-8", errors="replace", newline="") as fh:
        for r in csv.DictReader(fh):
            a = (r.get("Assignment") or "").strip().upper()
            o = (r.get("Organization Name") or "").strip()
            if len(a) == 6: rows.append((a, o))
    entries = []   # (oui24-hex, vendorIdx)
    seen = set()
    for vi, (label, pat, cap) in enumerate(VENDORS):
        rx = re.compile(pat, re.I); k = 0
        for a, o in rows:
            if k >= cap: break
            if a in seen: continue
            if rx.search(o): entries.append((a, vi)); seen.add(a); k += 1
    entries.sort(key=lambda e: e[0])                 # sorted for binary search
    L = ",\n  ".join('"%s"' % v[0] for v in VENDORS)
    T = "\n".join("  {0x%s, %d}," % (a, vi) for a, vi in entries)
    OUT.write_text(
f'''// GENERATED by tools/gen_hud_oui.py from the IEEE OUI registry -- do not hand-edit.
// Each OUI->vendor pair is the IEEE MA-L assignment; check_hud_oui.py re-verifies
// every row against the registry. Drone makers are included in full; the big
// phone/router brands are capped, so a miss just means "no hint", never a wrong one.
#include "hud_oui.h"
#include <string.h>

static const char* const VENDORS[] = {{
  {L}
}};
struct Oui {{ uint32_t oui; uint8_t v; }};
static const Oui TABLE[] = {{
{T}
}};
#define NOUI ((int)(sizeof(TABLE) / sizeof(TABLE[0])))

const char* hud_oui_vendor(const uint8_t mac[6]) {{
  if (mac[0] & 0x02) return "RANDOMIZED";          // locally-administered = privacy MAC
  uint32_t k = ((uint32_t)mac[0] << 16) | ((uint32_t)mac[1] << 8) | mac[2];
  int lo = 0, hi = NOUI - 1;                        // binary search (TABLE is sorted)
  while (lo <= hi) {{
    int m = (lo + hi) / 2;
    if (TABLE[m].oui == k) return VENDORS[TABLE[m].v];
    if (TABLE[m].oui < k) lo = m + 1; else hi = m - 1;
  }}
  return nullptr;                                   // unknown -> no hint
}}
''', encoding="utf-8")
    print("wrote %s: %d OUIs, %d vendors" % (OUT, len(entries), len(VENDORS)))
    return 0
if __name__ == "__main__": sys.exit(main())
