#!/usr/bin/env python3
"""Put the owl inside pueo-enclosure.scad, so the source is one file.

The lid debosses the logo, and the source did it with
`import("pueo-owl.svg")`. That makes the .scad useless on its own: download
it without the SVG beside it and it will not render. Anyone offered "the
source" was really being offered two files and a rule about where to put
them.

pueo-owl.svg is a single path of nothing but M, L and Z -- 32 closed
polygons, no curves at all, because tools/trace_logo.py emits polylines. So
it converts to an OpenSCAD polygon() exactly rather than approximately, and
the .scad can carry its own artwork.

The SVG stays the source of truth. This regenerates the block between the
two markers in the .scad, so editing the artwork means re-running this, not
hand-patching coordinates.

    python tools/inline_logo.py            rewrite the block
    python tools/inline_logo.py --check    fail if it is out of date

Equivalence is not assumed. The owl is debossed 0.6 mm deep into the lid, so
it removes a specific volume; render the lid before and after and compare.
The docstring on owl2d() records the number and how it was arrived at.
"""
import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SVG = os.path.join(REPO, "docs", "pueo", "pueo-owl.svg")
SCAD = os.path.join(REPO, "docs", "pueo", "pueo-enclosure.scad")

BEGIN = "/* ---------- owl artwork, generated by tools/inline_logo.py ---------- */"
END = "/* ---------- end generated owl artwork ---------- */"


def parse_path(d):
    """The subpaths of a path made only of M, L and Z."""
    polys, cur = [], []
    for cmd, args in re.findall(r"([MLZmlz])([^MLZmlz]*)", d):
        nums = [float(n) for n in re.findall(r"-?\d+\.?\d*(?:[eE][-+]?\d+)?", args)]
        if cmd in "Zz":
            if len(cur) >= 3:
                polys.append(cur)
            cur = []
        elif cmd in "Mm":
            if len(cur) >= 3:
                polys.append(cur)
            cur = [(nums[0], nums[1])]
            for i in range(2, len(nums), 2):          # extra pairs after M are L
                cur.append((nums[i], nums[i + 1]))
        else:
            for i in range(0, len(nums), 2):
                cur.append((nums[i], nums[i + 1]))
    if len(cur) >= 3:
        polys.append(cur)
    return polys


def build():
    svg = io.open(SVG, encoding="utf-8", errors="replace").read()
    ds = re.findall(r'\sd="([^"]+)"', svg)
    if len(ds) != 1:
        raise SystemExit("expected one <path>, found %d" % len(ds))
    if re.search(r"[CcSsQqTtAaHhVv]", ds[0]):
        raise SystemExit("the path has curves; this only handles M/L/Z")

    polys = parse_path(ds[0])

    # SVG's y runs down and OpenSCAD's runs up, and import(center = true)
    # centres on the bounding box. Both are reproduced here so the inlined
    # artwork lands exactly where the import did.
    xs = [p[0] for poly in polys for p in poly]
    ys = [p[1] for poly in polys for p in poly]
    cx = (min(xs) + max(xs)) / 2.0
    cy = (min(ys) + max(ys)) / 2.0

    pts, paths, n = [], [], 0
    for poly in polys:
        idx = []
        for x, y in poly:
            pts.append((round(x - cx, 3), round(cy - y, 3)))
            idx.append(n)
            n += 1
        paths.append(idx)

    out = [BEGIN,
           "/*", " * %d closed polygons, %d points, straight out of" % (len(paths), len(pts)),
           " * docs/pueo/pueo-owl.svg. Do not hand-edit: change the SVG and re-run",
           " * tools/inline_logo.py. The SVG is still published beside the source",
           " * for anyone who wants the artwork itself.",
           " *",
           " * y is flipped and the outline is centred on its own bounding box,",
           " * which is what import(center = true) did.",
           " */",
           "owl_points = ["]
    for i in range(0, len(pts), 6):
        row = ", ".join("[%g,%g]" % p for p in pts[i:i + 6])
        out.append("  " + row + ("," if i + 6 < len(pts) else ""))
    out.append("];")
    out.append("owl_paths = [")
    for j, idx in enumerate(paths):
        body = ",".join(str(i) for i in idx)
        out.append("  [" + body + "]" + ("," if j + 1 < len(paths) else ""))
    out.append("];")
    out.append("")
    out.append("module owl_outline() { polygon(points = owl_points, paths = owl_paths); }")
    out.append(END)
    return "\n".join(out), len(paths), len(pts)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    block, npaths, npts = build()
    src = io.open(SCAD, encoding="utf-8", newline="").read()
    nl = "\r\n" if src.count("\r\n") > src.count("\n") - src.count("\r\n") else "\n"

    if BEGIN in src:
        i, j = src.index(BEGIN), src.index(END) + len(END)
        new = src[:i] + block.replace("\n", nl) + src[j:]
    else:
        raise SystemExit("markers not found in %s; add them first" % SCAD)

    if args.check:
        if new != src:
            print("pueo-enclosure.scad's owl block is out of date; "
                  "run tools/inline_logo.py", file=sys.stderr)
            return 1
        print("owl block matches pueo-owl.svg (%d polygons, %d points)"
              % (npaths, npts))
        return 0

    io.open(SCAD, "w", encoding="utf-8", newline="").write(new)
    print("inlined %d polygons, %d points" % (npaths, npts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
